insert into customer (id_user, name, nif, adress, email, password) values (1, 'Del Maddick', 272723389, '85 Kipling Crossing', 'dmaddick0@posterous.com', 'zUeWpD1vyTs');
insert into customer (id_user, name, nif, adress, email, password) values (2, 'Ophelia Barson', 285448224, '50851 7th Crossing', 'obarson1@mtv.com', 'ntex4g');
insert into customer (id_user, name, nif, adress, email, password) values (3, 'Blaine Klimko', 148261745, '43 Everett Center', 'bklimko2@gizmodo.com', 'fYkLN61Ij');
insert into customer (id_user, name, nif, adress, email, password) values (4, 'Oralie Parfitt', 584176182, '4 Blackbird Pass', 'oparfitt3@amazon.com', 'jrheVXC');
insert into customer (id_user, name, nif, adress, email, password) values (5, 'Mollie Bissatt', 232372469, '5 Erie Place', 'mbissatt4@guardian.co.uk', 'nA1yvuXTkO');
insert into customer (id_user, name, nif, adress, email, password) values (6, 'Gary Kennady', 265584420, '75309 Algoma Point', 'gkennady5@yellowbook.com', 'j2ENqO');
insert into customer (id_user, name, nif, adress, email, password) values (7, 'Bren Yankin', 599069900, '7495 Carioca Terrace', 'byankin6@ft.com', '4zQHdQH');
insert into customer (id_user, name, nif, adress, email, password) values (8, 'Myranda Toffolini', 301610159, '250 Tennyson Terrace', 'mtoffolini7@fotki.com', 'eKVXBNIF');
insert into customer (id_user, name, nif, adress, email, password) values (9, 'Horatia Quayle', 937825418, '54244 Old Gate Center', 'hquayle8@bizjournals.com', 'WjFexE');
insert into customer (id_user, name, nif, adress, email, password) values (10, 'Flem Jelf', 110339039, '089 Graceland Circle', 'fjelf9@mtv.com', 'uA3NtGdkO7');
insert into customer (id_user, name, nif, adress, email, password) values (11, 'Sasha McKaile', 685996526, '1250 Meadow Valley Junction', 'smckailea@moonfruit.com', 'gRy8DBmSA09U');
insert into customer (id_user, name, nif, adress, email, password) values (12, 'Nero Goodrich', 736381825, '3 Golf Course Road', 'ngoodrichb@gnu.org', 'EKkdGjr');
insert into customer (id_user, name, nif, adress, email, password) values (13, 'Roana Milam', 860878091, '15523 Nancy Point', 'rmilamc@woothemes.com', 'dr2PGv');
insert into customer (id_user, name, nif, adress, email, password) values (14, 'Leeanne Duffree', 528482169, '72887 Ryan Trail', 'lduffreed@dion.ne.jp', 'iEMSqnYt');
insert into customer (id_user, name, nif, adress, email, password) values (15, 'Meagan Gainsford', 594538470, '87996 Delladonna Crossing', 'mgainsforde@columbia.edu', 'EpgcQJB');
insert into customer (id_user, name, nif, adress, email, password) values (16, 'Bryn Parradye', 932864561, '47303 Onsgard Park', 'bparradyef@ucla.edu', 'bidfOy');
insert into customer (id_user, name, nif, adress, email, password) values (17, 'Fayre Giovanetti', 622066927, '4413 Atwood Hill', 'fgiovanettig@weibo.com', '3Bt5Wn');
insert into customer (id_user, name, nif, adress, email, password) values (18, 'Hyacinthie Disney', 852113737, '92425 Meadow Valley Point', 'hdisneyh@netvibes.com', 'oW8sCtPRP');
insert into customer (id_user, name, nif, adress, email, password) values (19, 'Eustacia Allcock', 625618630, '7 Lyons Road', 'eallcocki@oakley.com', 'xXRLMRsj0a');
insert into customer (id_user, name, nif, adress, email, password) values (20, 'Lula Poone', 485495055, '5 Cherokee Way', 'lpoonej@dion.ne.jp', 'ScfYZTkGIR15');
insert into customer (id_user, name, nif, adress, email, password) values (21, 'Clay Wanka', 884340074, '201 Melrose Court', 'cwankak@nih.gov', 'a1mgr9PRCKNS');
insert into customer (id_user, name, nif, adress, email, password) values (22, 'Talia Holton', 145752876, '012 Morning Point', 'tholtonl@mlb.com', 'CVRL8odlAVo');
insert into customer (id_user, name, nif, adress, email, password) values (23, 'Shawnee Kilian', 263366186, '8612 Kenwood Plaza', 'skilianm@amazon.co.uk', '1rCd2L');
insert into customer (id_user, name, nif, adress, email, password) values (24, 'Raul Loukes', 268627961, '62773 Scofield Avenue', 'rloukesn@springer.com', 'sR9nDq');
insert into customer (id_user, name, nif, adress, email, password) values (25, 'Jarrod Maryet', 173515464, '44 Buena Vista Street', 'jmaryeto@163.com', '6SsV4L');
insert into customer (id_user, name, nif, adress, email, password) values (26, 'Edwin Keays', 747034400, '591 Scofield Hill', 'ekeaysp@cafepress.com', 'Ur7xDqt');
insert into customer (id_user, name, nif, adress, email, password) values (27, 'Merrile Pessold', 104455938, '262 Beilfuss Alley', 'mpessoldq@last.fm', '6pmfhSz');
insert into customer (id_user, name, nif, adress, email, password) values (28, 'Carney De Cleyne', 814980056, '8334 Golden Leaf Circle', 'cder@storify.com', 'xwFkw6A8X0');
insert into customer (id_user, name, nif, adress, email, password) values (29, 'Gail Gregan', 260446971, '888 North Junction', 'ggregans@skyrock.com', 'WAYIAci6be');
insert into customer (id_user, name, nif, adress, email, password) values (30, 'Biddy Ielden', 229129738, '62 Summit Center', 'bieldent@ucla.edu', 'XmkO6SOE8fY');